Фикс документации

diff --git a/.github/workflows/doc.yml b/.github/workflows/doc.yml
--- a/.github/workflows/doc.yml
+++ b/.github/workflows/doc.yml
@@ -1,17 +1,42 @@
-name: doc-deploy
+name: CI
 
 on:
   push:
-    branches:
+    branches:    
       - master
 
 jobs:
-  deploy:
+  build:
+
     runs-on: ubuntu-latest
-    docs:
-        runs-on: ubuntu-latest
-        steps:
-        - uses: actions/checkout@v1
-        - uses: ammaraskar/sphinx-action@master
-          with:
-            docs-folder: "docs/"
+
+    steps:
+    - name: Installing dep
+      run: |
+        pip install sphinx_rtd_theme
+        
+    - uses: actions/checkout@v1
+    # Standard drop-in approach that should work for most people.
+    - uses: ammaraskar/sphinx-action@master
+      with:
+        docs-folder: "./Software engineering/1.1"
+    # Publish built docs to gh-pages branch.
+    # ===============================
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
+        cp -r ./Software\ engineering/1.1/build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "sapfir999999@yandex.ru"
+        git config --local user.name "Sapfir0"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+    # ===============================
